# Generated by Django 3.2.7 on 2021-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='codigo',
            field=models.CharField(default='-', max_length=6),
        ),
        migrations.AddField(
            model_name='venda',
            name='codigo',
            field=models.CharField(default='-', max_length=6),
        ),
    ]
