# Generated by Django 3.2.7 on 2021-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_auto_20210910_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='valor_carrinho',
            field=models.FloatField(default=0),
        ),
    ]
